### ISSUE TITLE
Support comments

### ISSUE THREAD

**Issue by ehmicky** [groupon/cson-parser#29]
Support comments, like YAML but with the CoffeeScript syntax:

    # inline comment
    
    ###
    block comment
    ###

    ### block comment ###

If you find this interesting, I might consider working on a pull request.

**Comment by jkrems** [comment]
Thanks! Actually comments should already be supported, see [the following tests](https://github.com/groupon/cson-parser/blob/master/test/parse.coffee#L48-L62):

```coffee
  it 'allows line comments', ->
    compilesTo 'true # line comment', true

  it 'allows multi-line comments', ->
    compilesTo(
      """
      a:
        ###
        This is a comment
        spanning multiple lines
        ###
        c: 3
      """
      { a: { c: 3 } }
    )
```

Did you have something else in mind? Did you try some file and it didn't work? If so: could you share a failing example?

**Comment by ehmicky** [comment]
I am embarrassed to see it actually is. Sorry for the disturbance, and thanks for this parser, it makes conf files much better to read :+1:

**Comment by jkrems** [comment]
No worries! And thanks, nice to hear it's useful to people. :)
