### ISSUE TITLE
stringify defaulting to JSON

### ISSUE THREAD

**Issue by charlierudolph** [groupon/cson-parser#36]
Why does the stringify method default to JSON if the indentation level is falsey? 
This in unexpected and seems unnecessary as you could create valid minified cson

**Comment by jkrems** [comment]
Hi! Thanks for bringing this up!

I don't think there's a specific reason. It was just the easiest way to implement it at the time. And when everything is formatted as one line, human readable and -editable becomes pretty abstract. That being said: if someone would want to take this on and create a more minimal single-line representation I don't think anything would speak against merging it.

**Comment by johan** [comment]
Yeah, it was mostly incidental – no special intent besides ease of implementation and nobody having skin in the game about what non-indented cson should look like, as we mainly have been interested in cson as a human-consumption-friendly tidy subset of yaml. Aspirations, discussions and pull requests cordially invited, especially at a lovely civil level like this. :-)
