### ISSUE TITLE
fs-cson: new module using cson-parser

### ISSUE THREAD

**Issue by charlierudolph** [groupon/cson-parser#38]
In the spirit of the micro-library you have created here, I created another micro-library that encapsulating reading and writing cson to the filesystem. I was wondering if you could add it to your list of libraries. 

[fs-cson](https://github.com/charlierudolph/fs-cson)

Differences: 
* CSON is missing a function to write to the filesystem and seems way to complicated to me
* season will write JSON if the filePath doesn't end in `.cson` and has a lot of unrelated json support as well

**Comment by jkrems** [comment]
Nice! Could you create a PR adding it?
