### ISSUE TITLE
Terse syntax proposal for array of objects

### ISSUE THREAD

**Issue by jmatsushita** [groupon/cson-parser#40]
Hi there,

Currently this:

```
{
  "name": "test",
  "child_strings": [
    "child_string_1",
    "child_string_2"
  ],
  "child_objects": [
    {
      "name": "child_obj_1",
      "other": "key"
    },
    {
      "name": "child_obj_2",
      "another": "value"
    }
  ]
}
```

is in CSON:

```
name: "test"
child_strings: [
	"child_string_1"
	"child_string_2"
]
child_objects: [
	{
		name: "child_obj_1"
		other: "key"
	}
	{
		name: "child_obj_2"
		another: "value"
	}
]
```

The array of strings (```child_strings```) is nice and terse but the array of objects (```child_objects```) feels like only an incremental improvement on JSON's ceremony (for instance making copy pasting possibly slightly more error prone, which I guess is a good benchmark of usability). I was wondering if there could be a more terse notation for object children (of course ideally backwards compatible and without being a parsing nightmare) such as:

```
name: "test"
child_strings: [
	"child_string_1"
	"child_string_2"
]
child_objects: [
	name: "child_obj_1"
	other: "key"

	name: "child_obj_2"
	another: "value"
]
```

Currently this meaningful extra newline parses back into JSON the same way as the same CSON without the extra newline:
```
{
  "name": "test",
  "child_strings": [
    "child_string_1",
    "child_string_2"
  ],
  "child_objects": [
    {
      "name": "child_obj_2",
      "other": "key",
      "another": "value"
    }
  ]
}
```

So without the newline, the parser could interpret the keys as belonging to the same object (which happens to be the only element in this array), and with the double newline, it would be interpreted as starting a new array element (like a single newline in the ```child_string``` case). Would that be consistent with the current CSON philosophy and not break large amounts of existing CSON?

By the way this JSON:
```
[
  {
    "name": "child_obj_1",
    "other": "key"
  },
  "child_obj_string_1",
  "child_obj_string_2"
]
```

Currently parses into this CSON
```
[
	{
		name: "child_obj_1"
		other: "key"
	}
	"child_obj_string_1"
	"child_obj_string_2"
]
```

And with this proposal would be equivalent to this CSON
```
[
	name: "child_obj_1"
	other: "key"

	"child_obj_string_1"
	"child_obj_string_2"
]
```

A counter argument I could see, would be that the semantic of that extra newline might be different in the context of an object (where it might be best ignored) and in the context of an array (where it would be significant). That might create confusion. Maybe there's another, more backward compatible, still terse and elegant option?

**Comment by johan** [comment]
If cson is supposed to be syntax compatible with coffee-script (it currently is – compatible, I mean), these ideas simply are not options, for the very arguments you state.

I agree there is a definite lack of beauty in cson object arrays today, but it's very clear what things mean. Your last example, to me, reduces clarity, by making splatted object members seem at the same depth as the string items at the end:

```cson
[
    name: "child_obj_1"
    other: "key"

    "child_obj_string_1"
    "child_obj_string_2"
]
```

**Comment by jkrems** [comment]
Another counter argument for using a newline:

```cson
someLogic: 'group'
ofOptions: 'here'

followed: 'by'
another: 'one'
```

Especially in config files using new lines for logical grouping/clustering is pretty common (at least from what I've seen). It would be very confusing if this would suddenly produce an array of two objects.

Did you know that the following already works?

```cson
[
  a: 1
  b: 2
,
  c: 3
  d: 4
]
```

It's close to your proposal but has an explicit comma to signal the beginning of a new array element.

**Comment by jmatsushita** [comment]
@johan I understand. Breaking CS compatibility indeed seems like a no-no. 

@jkrems You're right that with non-"machine meaningful" spaces can be most human meaningful for readability. No, I didn't know that the comma notation existed and it does solve my problem! I guess it is a matter of taste, I do like the comma better (for now at least) :)

Mix and matching the comma notation for object and the newline for strings also works. 
```
[
  a: 1
  b: 2
,
  c: 3
  d: 4
, 
  'test'
  2 
]
```
I guess to me these children strings and children objects are at the same level if you don't see objects as adding an additional level.
