### ISSUE TITLE
stringify omits {}

### ISSUE THREAD

**Issue by braco** [groupon/cson-parser#44]
Why does stringify omit {} on objects? Is this intentional?

```
coffee> cson.stringify cson.parse "{foo: 'bar'}"
'foo:"bar"'
```

```
coffee> JSON.stringify cson.parse "{foo: 'bar'}"
'{"foo":"bar"}'
```

**Comment by jkrems** [comment]
Yes, this is intentional. The string representation is meant to be minimal and omit optional elements. If you need valid JSON as your output, `CSON.stringify` won't do the trick. Is there a particular use case where omitting `{}` causes problems for you?

**Comment by johan** [comment]
As for the why question, it is more terse, still syntactically legal, valid cson, and it made us happy. :-)

(Maybe not in that order.)

**Comment by braco** [comment]
The use case is in cson-loader for webpack, which needs valid JSON.
Bracketing manually would be a pain due to plain values like a string or
Boolean. I'll switch to JSON.stringify.

If valid JSON isn't the goal, probably remove the note about parity in the
README and maybe rename the method to prettyPrint or something to that
effect?

**Comment by jkrems** [comment]
> If valid JSON isn't the goal, probably remove the note about parity in the README and maybe rename the method to prettyPrint or something to that effect? Seems I probably just misunderstood the intention. Thanks for the help.

This one: `Interface is identical to JSON.{parse,stringify}`? If so: what was meant is that the functions have the same names and take the same arguments, only that `CSON.parse` parses CSON instead of JSON and `CSON.stringify` generates CSON instead of JSON. But I can see that "interface is identical" might warrant more explanation. Will add clarification.

**Comment by JamenMarz** [comment]
Should be closed, this is by design and makes perfect sense.

**Comment by jkrems** [comment]
Agreed.
