### ISSUE TITLE
Update to CoffeeScript v1.10.0

### ISSUE THREAD

**Issue by balupton** [groupon/cson-parser#45]
Just realised that bevry/cson is using CoffeeScript ^1.9.3 where this is using 1.9.0, as such two versions of coffee-script end up getting installed.

Is the plan for cson-parser to always use a specific coffee-script version?

Eitherway, I'll update bevry/cson to use CoffeeScript ^1.9.0

**Comment by balupton** [comment]
bevry/cson v3.0.2 released which uses coffee-script ^1.9.0

**Comment by jkrems** [comment]
Sorry for that. Force of habit that we pinned it to one specific version of coffee-script (usually coffee-script is a dev dependency only and it doesn't bother anyone when it's pinned). We'll get that sorted out soon. :)

**Comment by jkrems** [comment]
v1.2.0
