### ISSUE TITLE
Renaming have cause atom to break

### ISSUE THREAD

**Issue by alfgaar** [groupon/cson-parser#48]
i'm trying to install atom on chakra linux, but npm fails in finding cson-safe with ENOENT...
it's ok for you to name your library whatever you want, but is it ok to do in a way that break somebody elses code?

**Comment by jkrems** [comment]
Hi @alfgaar. Sorry that you ran into problems with this. I suspect you are hitting a bug in npm that is triggered by `latest` being set to a pre-release version. I updated the tag to point to `cson-safe@v1.0.5` instead. Can you confirm that this fixes the issue?

**Comment by jkrems** [comment]
I assume this fixed the issue. Feel free to reopen if this is still happening!
