### ISSUE TITLE
Incompatibility with CoffeeScript v1.11

### ISSUE THREAD

**Issue by ukoloff** [groupon/cson-parser#56]
I found that [this file](https://github.com/docpad/docpad/blob/master/locale/en.cson) 
  - is correctly parsed using CoffeeScript v1.10.0
  - fails with CoffeeScript v1.11.0 with error "Syntax error on line 3, column 13: Unexpected StringLiteral"

CoffeeScript's CHANGELOG mention:

>   Improved the internal representation of a CoffeeScript program. 
>  This is only noticeable to tools that use CoffeeScript.tokens or CoffeeScript.nodes.
>  Such tools need to update to take account for changed or added tokens and nodes.

May be it is the point!

**Comment by jkrems** [comment]
Thanks! Yes, you're spot on, it was the changes in the AST representation. I created #57 to address this. If you need an immediate fix, you could try pinning coffee-script in your application to 1.10.0. But I hope we'll get the proper patch out soon.

**Comment by jkrems** [comment]
Should be fixed w/ [v1.3.4](https://github.com/groupon/cson-parser/releases/tag/v1.3.4). Thanks for the report!
