### ISSUE TITLE
coffee-script renamed to coffeescript, update dependencies

### ISSUE THREAD

**Issue by tavikukko** [groupon/cson-parser#67]
https://www.npmjs.com/package/coffee-script

**Comment by jkrems** [comment]
Thanks a lot for the ping! Hadn't realized they changed the name of the package. We'll have to verify if the parser API changed during the 2.0 update.

**Comment by julmot** [comment]
I have the same situation. npm install fails due to this "UNMET DEPENDENCY"

**Comment by jkrems** [comment]
Oh, didn't realize they *removed* something from the registry..? I just tried and I can still install `cson-parser`.

@julmot Do you have a repro for that error? I tried installing `cson-parser` and it seems to work:

```
> npm i cson-parser

> coffee-script@1.12.8 postinstall /private/tmp/node_modules/coffee-script
> node --eval 'if (require("./package.json").name === "coffee-script") { var red, yellow, cyan, reset; red = yellow = cyan = reset = ""; if (!process.env.NODE_DISABLE_COLORS) { red = "\x1b[31m"; yellow = "\x1b[33m"; cyan = "\x1b[36m"; reset = "\x1b[0m"; } console.warn(red + "CoffeeScript has moved!" + reset + " Please update references to " + yellow + "\"coffee-script\"" + reset + " to use " + yellow + "\"coffeescript\"" + reset + " (no hyphen) instead."); console.warn("Also, a new major version has been released under the " + yellow + "coffeescript" + reset + " name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at " + cyan + "http://coffeescript.org" + reset + "."); console.warn(""); }'

CoffeeScript has moved! Please update references to "coffee-script" to use "coffeescript" (no hyphen) instead.
Also, a new major version has been released under the coffeescript name on NPM. This new release targets modern JavaScript, with minimal breaking changes. Learn more at http://coffeescript.org.

npm WARN saveError ENOENT: no such file or directory, open '/private/tmp/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/private/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

+ cson-parser@2.0.0
added 2 packages in 6.79s
```

Ignoring that super annoying warning they added.

**Comment by jkrems** [comment]
Ugh, they did the same thing that broke stuff all over the place with `babel`. Just... why..? :(

We'll see what we can do from our side but I would suggest locking yourself to a pre-warning version of `coffee-script` right now as a workaround.

**Comment by julmot** [comment]
> I would suggest locking yourself to a pre-warning version

Thanks for your reply. Can you please elaborate this a bit?

**Comment by julmot** [comment]
Ah I see @jkrems what you mean. Unfortunately I can't do that, since I'm not directly depending on cson-parser:

![topic](https://user-images.githubusercontent.com/8310677/33441530-2720787e-d5f3-11e7-9401-c407da899200.png)

So I guess everything I can do is wait until cson-parser depends on a backwards-compatible version, then I'd have to contact the owners of applause and grunt-replace to also update their dependencies and finally also wait for a grunt dependency update (https://github.com/gruntjs/grunt/issues/1611).

Or do you see any other way?

**Comment by julmot** [comment]
https://github.com/jashkenas/coffeescript/issues/4805

**Comment by julmot** [comment]
fyi: It works now, due to this fix: https://github.com/jashkenas/coffeescript/issues/4805#issuecomment-348237307

**Comment by mojavelinux** [comment]
Can we *please* get a new release of cson-parser? This warning is driving us all crazy. I get support tickets all the time that the install command for my application is broken because users think the warning means the install failed.

**Comment by mojavelinux** [comment]
Btw, I recognize that the coffee-script (or coffeescript) project screwed up, but it's done now and we have to deal with the problem that exists now.

**Comment by jkrems** [comment]
There should be a 3.0.0 soon that includes coffeescript.

P.S.: In case any Groupon employees read this: Please don't upgrade, we still have a bunch of `coffee-script` references in our dependency tree.

**Comment by mojavelinux** [comment]
@jkrems Thank you!
