### ISSUE TITLE
Add with yarn throw error

### ISSUE THREAD

**Issue by anthonybriand** [groupon/cson-parser#74]
When adding the module as a dependency to my project with Yarn the following error thrown : 
```
error cson-parser@4.0.0: The engine "yarn" is incompatible with this module. Expected version "0.0.0". Got "1.12.3"
```

This is related to the modification you have made in your package.json : 
https://github.com/groupon/cson-parser/blob/24a8ba813a6d494a0a00d52e43deeb00c42d090b/package.json#L21

Instead of "0.0.0" it will be at least to "^1.12.3"

**Comment by jkrems** [comment]
Thanks for bringing it up. The value `0.0.0` is chosen on purpose. See here for some context: https://github.com/groupon/cson-parser/pull/73#discussion_r231538808

We're definitely still looking for better ways to mark a library project as "not yarn compatible". Maybe removing the line and dealing with the resulting confusion instead would be a better trade-off. For the time being, adding the `ignore-engines` line to your project's `.npmrc` or yarn config should do the trick.

**Comment by jkrems** [comment]
Sorry, this kept getting buried in my inbox. I just pushed a change that removes the engines entry. We'll see that we update our automation to deal with this and/or find better ways to signal yarn that it shouldn't be used in this repo.
