### ISSUE TITLE
Pin Coffeescript dependency to 1.12.7

### ISSUE THREAD

**Issue by KingDarBoja** [groupon/cson-parser#89]
Hello cson-parser maintainers,

The current library is being used at [tslint-to-eslint-config](https://github.com/typescript-eslint/tslint-to-eslint-config) package to support Atom config files parsing in order to convert some options from TSLint to ESLint ones. However, we found that the current `coffeescript` dependency uses the minor semversion range (^) starting from `1.12.7`, which attempts to install the non-existent `1.12.8` version.

A ticket explaining such behaviour was opened on the repository with the reproduction steps:
https://github.com/typescript-eslint/tslint-to-eslint-config/issues/839

The correct behaviour should be to pin the dependency to `1.12.7` only to avoid such scenario.

Cheers!

**Comment by aaarichter** [comment]
Hey @KingDarBoja ,

thanks for raising this issue. I just opened a PR to freeze `coffeescript` to the given version.

**Comment by aaarichter** [comment]
the PR is merged and v4.0.7 is released. closing

**Comment by KingDarBoja** [comment]
That was fast! Thank you 🚀
